Fix: Message can't be encrypted with ethereum web3 provider
aleph-im/aleph-sdk-ts pull request #116
Opened 2023-01-10 16:42 UTC by Rgascoin

Related to: https://github.com/aleph-im/aleph-sdk-ts/issues/114

Working on implementation specifically [for metamask](https://docs.metamask.io/guide/rpc-api.html#unrestricted-methods).
As this feature was already implemented in the SDK, I think finishing the implementation can make sense here.

Besides this fix, this PR will also add a new feature to allow encryption testing inside the Toolshed. 

Be aware of the potential [security issue](https://medium.com/metamask/metamask-api-method-deprecation-2b0564a84686) using this method.

2023-02-20 09:57 UTC, BjrInt commented
Getting this error in the Toolshed app when trying to decrypt content with an Ethereum (and also oddly enough with a NULS2 account). Does not matter if this is instanciated from Metamask or from a Keypair (did not test it using a Ledger device yet).
![image](https://user-images.githubusercontent.com/26065817/220072696-e4c2be38-57b4-44ec-b6e6-0615e1b8677b.png)

2023-02-21 09:30 UTC, BjrInt requested changes

2023-02-21 10:50 UTC, Rgascoin commented on src/accounts/nuls2.ts
> +        });
Thanks, Fixed in: [5bd3d79](https://github.com/aleph-im/aleph-sdk-ts/pull/116/commits/5bd3d7969f09ec7bbca5e656740246314bbae7c0)

2023-02-21 10:50 UTC, Rgascoin commented on src/accounts/avalanche.ts
> +            });
Thanks, Fixed in: [5bd3d79](https://github.com/aleph-im/aleph-sdk-ts/pull/116/commits/5bd3d7969f09ec7bbca5e656740246314bbae7c0)

2023-02-21 10:51 UTC, Rgascoin commented on src/accounts/ethereum.ts
> +        }
Thanks, Fixed in: [5bd3d79](https://github.com/aleph-im/aleph-sdk-ts/pull/116/commits/5bd3d7969f09ec7bbca5e656740246314bbae7c0)

2023-02-21 12:57 UTC, Rgascoin commented on src/accounts/providers/JsonRPCWallet.ts
>      }
This function is also used for the encryption to detect if the metamask standards encryption is needed

2023-03-13 14:52 UTC, BjrInt approved these changes
LGTM

2023-03-13 14:52 UTC, merged